<?php

use Illuminate\Database\Seeder;

class MedicalstaffTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('medicalstaff')->delete();
        
        \DB::table('medicalstaff')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'first_name' => 'Ahmad',
                'second_name' => 'Tharwt',
                'third_name' => 'Ibraheem',
                'family_name' => 'Tharwt',
                'full_name' => 'Ahmad Tharwt Ibraheem Tharwt',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '168',
                'catgno' => '1',
                'depno' => '5',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '53714',
                'dob' => '1986-03-08',
                'gender' => 'M',
                'phone' => '581555930',
                'mobile' => '581555930',
                'address' => 'Qubaa St, next to alKaaki Mall',
                'licence_no' => 'sssaaa',
                'licence_expdate' => '2017-12-24',
                'med_actv' => NULL,
                'created_at' => '2017-12-24 16:25:15',
                'updated_at' => '2018-01-02 01:36:20',
            ),
            1 => 
            array (
                'id' => 5,
                'user_id' => 13,
                'first_name' => 'John',
                'second_name' => 'Adam',
                'third_name' => 'George',
                'family_name' => 'Miller',
                'full_name' => 'John Adam George Miller',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '196',
                'catgno' => '1',
                'depno' => '1',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '23423',
                'dob' => '1986-04-02',
                'gender' => 'F',
                'phone' => '048551693',
                'mobile' => '48551693',
                'address' => '1263 S CHILLICOTHE RD',
                'licence_no' => 'dvuwovuwovug',
                'licence_expdate' => '2017-12-18',
                'med_actv' => NULL,
                'created_at' => '2017-12-27 10:29:49',
                'updated_at' => '2017-12-30 13:39:41',
            ),
            2 => 
            array (
                'id' => 8,
                'user_id' => 14,
                'first_name' => 'Ayman',
                'second_name' => 'Mohammed',
                'third_name' => 'Ali',
                'family_name' => 'Mahjoub',
                'full_name' => 'Ayman Mohammed Ali Mahjoub',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '168',
                'catgno' => '3',
                'depno' => '6',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '63518',
                'dob' => '1982-03-10',
                'gender' => 'M',
                'phone' => '581555930',
                'mobile' => '581555930',
                'address' => 'Qubaa St, next to alKaaki Mall',
                'licence_no' => 'ewtbwrthwrtnwr',
                'licence_expdate' => '2017-09-05',
                'med_actv' => 'I',
                'created_at' => '2018-01-01 21:52:33',
                'updated_at' => '2018-01-01 21:54:03',
            ),
            3 => 
            array (
                'id' => 9,
                'user_id' => 15,
                'first_name' => 'AbdelMoneim',
                'second_name' => 'Mohamed',
                'third_name' => 'Islam',
                'family_name' => 'ElTokhy',
                'full_name' => 'AbdelMoneim Mohamed Islam ElTokhy',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '218',
                'catgno' => '4',
                'depno' => '2',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '73291',
                'dob' => '1953-01-18',
                'gender' => 'M',
                'phone' => '4403392600',
                'mobile' => '4403392600',
                'address' => '1263 S CHILLICOTHE RD, Suite 771-98',
                'licence_no' => 'dfsrnyneyeh',
                'licence_expdate' => '2020-01-25',
                'med_actv' => 'I',
                'created_at' => '2018-01-01 21:55:14',
                'updated_at' => '2018-01-01 21:56:35',
            ),
            4 => 
            array (
                'id' => 10,
                'user_id' => 16,
                'first_name' => 'Lamiaa',
                'second_name' => 'Salem',
                'third_name' => 'Ahmad',
                'family_name' => 'Ibraheem',
                'full_name' => 'Lamiaa Salem Ahmad Ibraheem',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '170',
                'catgno' => '4',
                'depno' => '23',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '12342',
                'dob' => '1955-01-18',
                'gender' => 'F',
                'phone' => '48551693',
                'mobile' => '48551693',
                'address' => 'Madinah Cardiac Center, Khalid bin Walid St, next to King Fahad Hospital',
                'licence_no' => '1243536 gffj',
                'licence_expdate' => '2019-01-18',
                'med_actv' => 'I',
                'created_at' => '2018-01-05 21:00:55',
                'updated_at' => '2018-01-05 21:05:10',
            ),
            5 => 
            array (
                'id' => 11,
                'user_id' => 17,
                'first_name' => 'Ismaeel',
                'second_name' => 'Mahmoud',
                'third_name' => 'Radi',
                'family_name' => 'Rida',
                'full_name' => 'Ismaeel Mahmoud Radi Rida',
                'first_name_ar' => NULL,
                'second_name_ar' => NULL,
                'third_name_ar' => NULL,
                'family_name_ar' => NULL,
                'full_name_ar' => '   ',
                'natno' => '187',
                'catgno' => '3',
                'depno' => '3',
                'jobno' => NULL,
                'dispno' => '1',
                'specno' => NULL,
                'empno' => '98765',
                'dob' => '1971-06-10',
                'gender' => 'M',
                'phone' => '48551693',
                'mobile' => '48551693',
                'address' => 'Madinah Cardiac Center, Khalid bin Walid St, next to King Fahad Hospital',
                'licence_no' => 'jhmcut6rsd684sd',
                'licence_expdate' => '2020-01-31',
                'med_actv' => 'I',
                'created_at' => '2018-01-05 23:57:53',
                'updated_at' => '2018-01-06 00:00:12',
            ),
        ));
        
        
    }
}